### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by dzakijo1** [ilmanhdyt/ShiraoriBOT#4]
![image](https://user-images.githubusercontent.com/47619660/145707008-57c703b8-2f04-4aa9-a84b-24f76bf9ef5c.png)
bang ini emang sering error gini ya? ada kontak WA ga bang mau nanya nanya

**Comment by ilmanhdyt** [comment]
> ![image](https://user-images.githubusercontent.com/47619660/145707008-57c703b8-2f04-4aa9-a84b-24f76bf9ef5c.png) bang ini emang sering error gini ya? ada kontak WA ga bang mau nanya nanya

Selama fiturnya bisa dipake itu tidak masalah 😎
